### ISSUE TITLE
Transitions Broken using GatsbyJS in Production build.

### ISSUE THREAD

**Issue by KevinMongiello** [transitive-bullshit/react-background-slideshow#3]
I'm using this app with GatsbyJS, a static site generator using React components, and was having a trouble getting the slider to work on production build (while working fine in development).

I opened an issue on their repo,
https://github.com/gatsbyjs/gatsby/issues/9110

I have been redirected to mention this here as it may be an issue with this library.

**Comment by transitive-bullshit** [comment]
Thanks for following up on this @KevinMongiello 😄 

I would recommend using @pieh's comment [here](https://github.com/gatsbyjs/gatsby/issues/9110#issuecomment-429899363).

This means that with SSR, you won't render the slideshow on the server but rather only render it once rehydration takes over the client-side.

We could make a change to this library to properly handle SSR, but I think it's just easier for your app to handle that logic itself.

**Comment by KevinMongiello** [comment]
Sure thing!
I think I got it.  I'm running with that workaround, and it seems to be fine. 
Thanks for the reply, and the package 😄
